call DB_FRAMEWORK.UTILS.SP_ADD_SHARING_REQUEST(
	'DODECOM-4432',
	'START_SHARING',
	['AW40842'],
	[
		'DB_SHR_PROVIDER_QAS.SHR_PL_INTERACTION_CONS.TDE_CONSUMER_INTERACTION',
		'DB_SHR_PROVIDER_QAS.SHR_PL_INTERACTION_CONS.MDE_CONSUMER_INTERACTION_DEVICE',
		'DB_SHR_PROVIDER_QAS.SHR_PL_INTERACTION_CONS.MDE_CONSUMER_INTERACTION_FLAVOUR',
		'DB_SHR_PROVIDER_QAS.SHR_PL_INTERACTION_CONS.MDE_CONSUMER_INTERACTION_PRODUCT',
		'DB_SHR_PROVIDER_QAS.SHR_PL_INTERACTION_CONS.MDE_CONSUMER_INTERACTION_VOUCHER'
	],
	'2099-01-01',
	'Ingrid.Wijaya@sampoerna.com',
	'PRESENTATION'
);
